//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfort_ClientApplication.UserWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserWebService.UserWebServiceSoap")]
    public interface UserWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string registerUser(string userID, string name, string address, string contactNumber, string email, string password, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> registerUserAsync(string userID, string name, string address, string contactNumber, string email, string password, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string autoUserID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> autoUserIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> loginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logout", ReplyAction="*")]
        System.Threading.Tasks.Task<string> logoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/assignDistributorToSeller", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string assignDistributorToSeller(string sellerID, string distributorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/assignDistributorToSeller", ReplyAction="*")]
        System.Threading.Tasks.Task<string> assignDistributorToSellerAsync(string sellerID, string distributorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDistributorIDForSellerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getDistributorIDForSellerID(string sellerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDistributorIDForSellerID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getDistributorIDForSellerIDAsync(string sellerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getUserDetails(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getUserDetailsAsync(string userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserWebServiceSoapChannel : CozyComfort_ClientApplication.UserWebService.UserWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWebServiceSoapClient : System.ServiceModel.ClientBase<CozyComfort_ClientApplication.UserWebService.UserWebServiceSoap>, CozyComfort_ClientApplication.UserWebService.UserWebServiceSoap {
        
        public UserWebServiceSoapClient() {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string registerUser(string userID, string name, string address, string contactNumber, string email, string password, string role) {
            return base.Channel.registerUser(userID, name, address, contactNumber, email, password, role);
        }
        
        public System.Threading.Tasks.Task<string> registerUserAsync(string userID, string name, string address, string contactNumber, string email, string password, string role) {
            return base.Channel.registerUserAsync(userID, name, address, contactNumber, email, password, role);
        }
        
        public string autoUserID() {
            return base.Channel.autoUserID();
        }
        
        public System.Threading.Tasks.Task<string> autoUserIDAsync() {
            return base.Channel.autoUserIDAsync();
        }
        
        public string login(string email, string password) {
            return base.Channel.login(email, password);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string email, string password) {
            return base.Channel.loginAsync(email, password);
        }
        
        public string logout() {
            return base.Channel.logout();
        }
        
        public System.Threading.Tasks.Task<string> logoutAsync() {
            return base.Channel.logoutAsync();
        }
        
        public string assignDistributorToSeller(string sellerID, string distributorID) {
            return base.Channel.assignDistributorToSeller(sellerID, distributorID);
        }
        
        public System.Threading.Tasks.Task<string> assignDistributorToSellerAsync(string sellerID, string distributorID) {
            return base.Channel.assignDistributorToSellerAsync(sellerID, distributorID);
        }
        
        public string getDistributorIDForSellerID(string sellerID) {
            return base.Channel.getDistributorIDForSellerID(sellerID);
        }
        
        public System.Threading.Tasks.Task<string> getDistributorIDForSellerIDAsync(string sellerID) {
            return base.Channel.getDistributorIDForSellerIDAsync(sellerID);
        }
        
        public System.Data.DataSet getUserDetails(string userID) {
            return base.Channel.getUserDetails(userID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getUserDetailsAsync(string userID) {
            return base.Channel.getUserDetailsAsync(userID);
        }
    }
}
